import Phaser from 'phaser';
import { type BucketLayout } from '../gameplay/physics-layout';
import { type DroppedFruit, type PendingMerge } from '../gameplay/merge-handler';
import { type ObstacleGameObject } from '../gameplay/obstacle-sprite';
import { type ObstacleState } from '../logic/obstacles';
import { type StageConfig } from '../logic/stages';
import { type HudElements } from '../gameplay/hud-manager';
import { type ActionBarElements } from '../gameplay/action-bar';
export declare class GameplayScene extends Phaser.Scene {
    gameMode: 'classic' | 'stage' | 'daily';
    stageId: number;
    stageConfig: StageConfig | undefined;
    stageDropsRemaining: number;
    stageDropsUsed: number;
    stageCreatedTiers: Map<number, number>;
    stageObstacleStates: ObstacleState[];
    stageObstacleObjects: Map<string, ObstacleGameObject>;
    stageVictoryCelebrated: boolean;
    fruits: DroppedFruit[];
    fruitsById: Map<number, DroppedFruit>;
    mergingFruitIds: Set<number>;
    pendingMerges: PendingMerge[];
    nextFruitId: number;
    layout: BucketLayout;
    ghostTier: number;
    ghostX: number;
    ghost: Phaser.GameObjects.Image;
    aimLine: Phaser.GameObjects.Graphics;
    dangerLine: Phaser.GameObjects.Graphics;
    hudElements: HudElements;
    actionBarElements: ActionBarElements | undefined;
    isHammerMode: boolean;
    isBombActiveNext: boolean;
    isRainbowActiveNext: boolean;
    isShakingBucket: boolean;
    isPaused: boolean;
    isPromptingRefill: boolean;
    gameOverTriggered: boolean;
    cosmicVictoryCelebrated: boolean;
    dailyVictoryCelebrated: boolean;
    hasClaimedDailyExtraDrops: boolean;
    wasNearDanger: boolean;
    lastMotionMs: number;
    lastUiClickTime: number;
    sceneStartTime: number;
    constructor();
    init(data?: {
        mode?: 'classic' | 'stage' | 'daily';
        isDailyMode?: boolean;
        isStageMode?: boolean;
        stageId?: number;
    }): void;
    create(): void;
    update(time: number, _delta: number): void;
    private getActionBarState;
    private getControllerState;
    private getControllerCallbacks;
    private getMergeProcessorCallbacks;
    private updateHudState;
    triggerGameOver(): void;
    isGameOver(): boolean;
    clearFruitsAboveDanger(): void;
    getLastMotionMs(): number;
    isNearDanger(): boolean;
    playSfx(key: string, volume?: number, detune?: number): void;
    private onPauseGame;
    private promptRefillPowerups;
    private showDailyExtraDropsModal;
}
